site_name: FENN
site_url: https://pyfenn.org/
site_description: FENN Friendly Environment for Neural Networks
site_author: PyFenn
docs_dir: src

theme:
  logo: images/logo.png
  favicon: images/logo.png
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - toc.integrate   # right-hand in-page TOC

  palette:
    scheme: default
    primary: custom
    accent: custom

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide:
    - Logging:
      - Local: user_guide/logging/local.md
      - Wandb: user_guide/logging/wandb.md
    - Notifications:
      - Basic Usage: user_guide/notifications/basic_usage.md
      - Discord: user_guide/notifications/discord.md
      - Telegram: user_guide/notifications/telegram.md
      - Email: user_guide/notifications/email.md
      - Slack: user_guide/notifications/slack.md
  - CLI:
    - Pull: CLI/pull.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyfenn/fenn
      name: Source on GitHub

extra_css:
  - css/extra.css

copyright: "Copyright &copy; 2025 PyFenn"